apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: engine-handler-3546
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/engine-handler-3546
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
